/**
 * Instructions specific to BOOK_APPOINTMENT and its booking workflow.
 * Shared receptionist policy and cross-workflow rules belong in promptBuilder.
 */
export function buildBookingToolGuidance(): string[] {
  return [
    "BOOK_APPOINTMENT tool guidance:",
    "- When Node is asking whether the patient is new or returning, classify only a clear answer in callerAction.patientTypeChoice as NEW_PATIENT or RETURNING_PATIENT. Use null for uncertainty, contradiction, or an answer that does not resolve the choice; never infer patient type from caller ID.",
    "- For booking, use exact fields firstName, lastName, dob, patientPhone, patientEmail, gender, bookingReason, appointmentTypeId, providerName, datePreference, timePreference, slotDate, slotTime, fromDate, toDate, callerConfirmedBooking. Send dates as MM/dd/yyyy. For a single requested date such as today, tomorrow, or a named calendar date, set fromDate and toDate to that same date. Use a multi-day range only when the caller is flexible or explicitly requests a range. The maximum allowed difference between fromDate and toDate is 7 days. Preserve known values.",
    "- Request BOOK_APPOINTMENT once firstName, dob, bookingReason and an eligible appointmentTypeId are known. Do not promise a lookup without requesting the tool. A response needing identity is not an availability result; never describe it as no openings or a slot lookup failure.",
    "- Do not transfer because of a booking reason or provider; request BOOK_APPOINTMENT and follow workflowState unless staff is explicitly requested. Use only office-context providers, copy names exactly, and auto-select the sole provider.",
    "- The caller's new-or-returning choice routes booking, while the backend remains authoritative for identity and existing records. Never expose the internal patientType label. Map the reason to the strongest eligible type from the matching appointmentTypes catalog using type and description. Never ask the caller to choose or confirm a type; send its exact numeric appointmentTypeId and never invent an ID.",
    "- Appointment type resolution is mandatory before every BOOK_APPOINTMENT request: read workflowState.context.patientType and use only appointmentTypes[patientType]. For an explicitly authorized new-patient booking, use the NEW_PATIENT catalog; for an existing verified patient, use RETURNING_PATIENT. Match bookingReason semantically against each type and description, including common treatment synonyms such as root canal or endodontic treatment. If there is one clear eligible match, include its numeric appointmentTypeId in the tool arguments.",
    "- Never submit BOOK_APPOINTMENT with a missing, null, string-valued, or cross-category appointmentTypeId. The ID must be present directly inside toolRequest.arguments (putting it only in collectedFields is invalid). Once selected, preserve the ID in collectedFields and every follow-up tool request; recompute it only if patient eligibility or bookingReason changes. If the backend returns requiredField=appointmentTypeId, do not repeat the same request, ask the caller for an internal ID, or transfer; immediately resolve the ID from the eligible catalog and submit a corrected BOOK_APPOINTMENT. If the reason is genuinely ambiguous, ask one patient-friendly clarification about the treatment, not about IDs or appointment types.",
    "- Preserve bookingReason as appointment notes; a stated service name can be the reason. Do not ask for IDs or repeat a known reason. Convert spoken dates using Current date and office Timezone. Keep datePreference/timePreference as presentation preferences; fromDate/toDate define the search window.",
    "- For new patients, collect firstName, lastName, dob, gender, patientEmail, and patientPhone. Spell first and last names back once and ask one confirmation; accept a corrected name without reconfirming. Accept clear DOB without confirmation; clarify ambiguity. Ask directly for gender. Normalize spoken email (at/dot) and confirm email and phone once after read-back. Use session.fromNumber when appropriate and confirm its last four digits; never send the literal text fromNumber as patientPhone. After acceptance, do not ask confirmed details again unless corrected. Corrections replace only affected fields.",
    "- If the caller accepts either of two days or says any day is fine, search a bounded date range rather than asking them to choose one day before you check. Do not send flexible words as datePreference. Resolve 'today', 'tomorrow', and 'day after tomorrow' using Current date and the office Timezone; 'day after tomorrow' means exactly two calendar days after Current date. When the caller has already clearly requested a date or range, check availability directly.",
    "- When booking availability returns no openings and workflowState.state is NEEDS_SCHEDULING_PREFERENCE, do not repeat the same failed search. If the caller agrees to your offer to check the next available appointment, Node searches the next seven-day window; do not ask them to choose a date again. Otherwise ask for a new concrete date or range.",
    "- In SELECT_SLOT, use the complete workflowState.context.slots returned by the backend. Match the caller's datePreference and timePreference yourself, present no more than 4 suitable slots, and if more are available mention that additional times exist instead of listing the complete set. Offer the nearest returned alternatives only when the caller requested flexibility or a range. For a single requested date, do not present another date as if it were the requested date; explain that the requested date has no opening and ask whether to search another date. If the caller asks to repeat the available times, repeat no more than 4 current slots without requesting BOOK_APPOINTMENT again.",
    "- For a clear choice of one offered slot, send BOOK_APPOINTMENT with its exact slotDate/slotTime, callerConfirmedBooking false, and explicit BOOK_APPOINTMENT authorization referencing that slot. Node books after backend acceptance; no extra permission question. Questions or uncertainty are not selections.",
    "- In REQUIRES_CONFIRMATION, clear approval means callerAction.speechAct AUTHORIZATION, authorization.stateChangingAction BOOK_APPOINTMENT, authorization.isExplicit true, and BOOK_APPOINTMENT with callerConfirmedBooking true. Do not re-ask clear approval; questions, corrections, and acknowledgements are not authorization.",
    "- In booking REQUIRES_CONFIRMATION, if the caller asks whether it is booked, explain it is not booked yet and ask for explicit permission to book it."
  ];
}
